# Generated by Django 5.0.7 on 2024-07-14 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.TextField()),
                ('topic', models.TextField()),
                ('insight', models.TextField()),
                ('url', models.TextField()),
                ('region', models.TextField()),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('impact', models.TextField()),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.TextField()),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.TextField()),
                ('source', models.TextField()),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datapoint',
            },
        ),
    ]
